import { createApp } from "vue";
import App from "./App.vue";
import router from "./router/index.js";
import "bootswatch/dist/lux/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "bootstrap-icons/font/bootstrap-icons.css";
import { createPinia } from "pinia";
import "notyf/notyf.min.css";
const app = createApp(App);
app.use(router);
app.use(createPinia());
app.mount("#app");
